### ISSUE TITLE
module 'distutils' has no attribute 'distutils_path'

### ISSUE THREAD

**Issue by hxnoyd** [carbonblack/cb-yara-connector#27]
Hi. I get the following error when building the binary with pyinstaller:

```
# pyinstaller main.spec
34 INFO: PyInstaller: 3.5
34 INFO: Python: 3.6.8
35 INFO: Platform: Linux-4.9.184-linuxkit-x86_64-with-centos-7.7.1908-Core
39 INFO: UPX is available.
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.5', 'console_scripts', 'pyinstaller')()
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "main.spec", line 2, in <module>
    if distutils.distutils_path.endswith('__init__.py'):
AttributeError: module 'distutils' has no attribute 'distutils_path'
```

Any suggestions on what might be causing this?
Thanks in advance!

**Comment by kainjow** [comment]
On a completely unrelated project, I hit this same error with a spec file, but am using a custom Python build. After disabling these lines, PyInstaller ran into issues trying to find the Python library files. I had to rebuild Python with `--enable-shared` and now things seem to be working. Might be some hints for you.
