### ISSUE TITLE
error to connect to /connector/yara

### ISSUE THREAD

**Issue by ghost** [carbonblack/cb-yara-connector#35]
i am installed EDR 7.1 with last released of cb-yara-connector and install cb-yara-manager the service up and running correctly but when i am access the WUI http://server/connector/yara i got this error 

Traceback (most recent call last):
  File "app/routes.py", line 59, in wrapped_f
  File "site-packages/werkzeug/exceptions.py", line 525, in __call__
Unauthorized: 401: Unauthorized
127.0.0.1 - - [24/Jun/2020 17:58:01] "GET /connector/yara/ HTTP/1.0" 401 - 

any help Please regarding this error

**Comment by ghost** [comment]
e
